django_app/urls.py
from django.contrib import admin
from django.urls import path, include
#import hello.views as hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include('hello.urls', namespace="hello")),
]

hello/urls.py
from django.urls import path
from .views import IndexView, NameListView, NameDetailView, SendMailView

app_name = 'hello'

urlpatterns = [
    path('', IndexView.as_view()),
    path('list/', NameListView.as_view(), name='namelist'),
    path('detail/<int:pk>/', NameDetailView.as_view(), name='namedetail'),
    path('sendmail/', SendMailView.as_view(), name='sendmail'),
    ]

hello/models.py
from django.db import models

# Create your models here.
class Hello(models.Model):
    name = models.CharField(max_length=10)
    
    def __str__(self):
        return self.name

hello/views.py
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView 
from .models import Hello
from django.shortcuts import redirect
from django.core.mail import send_mail

class IndexView(TemplateView):
    template_name = "hello/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['one_name'] = Hello.objects.all()[0]
        return context

class NameListView(ListView):
    model = Hello
    
class NameDetailView(DetailView):
    model = Hello
    
class SendMailView(DetailView):
    #template_name = "hello/buy_item.html"
    
    def get(self, request):
        self.send_order_mail()      
        return redirect('hello:namelist')
    
    def send_order_mail(self):
        
        """題名"""
        subject = f"商品注文のお願い"
        """本文"""
        message = (
            "いつもお世話になっております。\n"
            )

        """送信元メールアドレス（企業DBから取得）"""
        from_email = "t21cs024@gmail.com"
        
        """宛先メールアドレス（企業DBから取得）"""
        recipient_list = [
            "tt342772@gmail.com"
            ]
        send_mail(subject, message, from_email, recipient_list)

hello/templates/hello/hello_detail.html
<html>
<body>
<p> Hello {{ object.name }} ! </p>
</body>
</html>

hello/templates/hello/hello_list.html
<html>
<body>
<ul>
{% for object in object_list %}
<li>
 <a href="{% url 'hello:namedetail' pk=object.id %}">{{ object }}</a>
</li>
{% endfor %}
</ul>
</body>
</html>

hello/templates/hello/index.html
{% load static %}

  <link rel="stylesheet" href="{% static '/bootstrap/css/self-made.css' %}">


{% block main %}

<p> Hello {{ one_name }} </p>

<div class="btn">
 <a href="">aaa</a></div>
 
 		<a href="">
	  		<button class="buck-btn" type="button">戻る</button>
		</a>


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang = "ja">
<head>
  <meta charset = "utf-8">
  <meta name = "viewport" content = "width = device - width, initial - scale = 1.0">
  <title>{% block title %} 買い物リスト メインページ {% endblock %}</title>
  <link rel = "stylesheet" href = "{% static '/bootstrap/css/bootstrap.min.css'%}">
</head>
<body>
  <div class = "container">
  <nav class = "nav">
    <div class = "navber-brand">MyPage</div>
  </nav>
  </div>
  {% block main %}{% endblock %}
  </body>
</html>